spring:
  application:
    name: order-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1100/eureka/
server:
  port: 8002
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false